<?php
/**
 * GENERATED by generate.php. Do not hand-edit goldens.
 *
 * Characterization of mai_get_dom_document() + mai_get_dom_html() as they ship TODAY,
 * defects included. Groups g3 and g7 pin dangerous behavior deliberately; see the
 * security finding in docs/superpowers/specs/2026-07-30-wordpress-phpunit-suite-design.md.
 */

return [
	'g1_polish_diacritics' => [
		'in'  => "<p>Za\u{17C}\u{F3}\u{142}\u{107} g\u{119}\u{15B}l\u{105} ja\u{17A}\u{144}</p>",
		'out' => "<p>Za\u{17C}\u{F3}\u{142}\u{107} g\u{119}\u{15B}l\u{105} ja\u{17A}\u{144}</p>\n",
	],
	'g1_curly_quotes' => [
		'in'  => "<p>\u{201C}quoted\u{201D} and \u{2018}single\u{2019} and it\u{2019}s</p>",
		'out' => "<p>\u{201C}quoted\u{201D} and \u{2018}single\u{2019} and it\u{2019}s</p>\n",
	],
	'g1_dashes' => [
		'in'  => "<p>a \u{2014} b \u{2013} c</p>",
		'out' => "<p>a \u{2014} b \u{2013} c</p>\n",
	],
	'g1_entity_amp' => [
		'in'  => "<p>&amp;</p>",
		'out' => "<p>&</p>\n",
	],
	'g1_entity_lt_gt' => [
		'in'  => "<p>&lt;tag&gt;</p>",
		'out' => "<p><tag></p>\n",
	],
	'g1_entity_quot' => [
		'in'  => "<p>&quot;q&quot;</p>",
		'out' => "<p>\u{22}q\u{22}</p>\n",
	],
	'g1_entity_apos' => [
		'in'  => "<p>&#039;a&#039;</p>",
		'out' => "<p>'a'</p>\n",
	],
	'g1_entity_nbsp' => [
		'in'  => "<p>a&nbsp;b</p>",
		'out' => "<p>a\u{A0}b</p>\n",
	],
	'g1_double_escaped' => [
		'in'  => "<p>&amp;amp;</p>",
		'out' => "<p>&amp;</p>\n",
	],
	'g1_bare_ampersand' => [
		'in'  => "<p>Tom & Jerry</p>",
		'out' => "<p>Tom & Jerry</p>\n",
	],
	'g1_amp_in_href' => [
		'in'  => "<a href=\u{22}?a=1&amp;b=2\u{22}>link</a>",
		'out' => "<a href=\u{22}?a=1&b=2\u{22}>link</a>\n",
	],
	'g1_emoji_bmp' => [
		'in'  => "<p>\u{2615}</p>",
		'out' => "<p>\u{2615}</p>\n",
	],
	'g1_emoji_astral' => [
		'in'  => "<p>\u{1F389}</p>",
		'out' => "<p>\u{1F389}</p>\n",
	],
	'g1_emoji_zwj' => [
		'in'  => "<p>\u{1F469}\u{200D}\u{1F4BB}</p>",
		'out' => "<p>\u{1F469}\u{200D}\u{1F4BB}</p>\n",
	],
	'g1_numeric_entity' => [
		'in'  => "<p>&#380;</p>",
		'out' => "<p>\u{17C}</p>\n",
	],
	'g1_nested_markup' => [
		'in'  => "<p><strong>bold</strong> and <em>italic</em></p>",
		'out' => "<p><strong>bold</strong> and <em>italic</em></p>\n",
	],
	'g1_combined' => [
		'in'  => "<p>Za\u{17C}\u{F3}\u{142}\u{107} &amp; \u{201C}curly\u{201D} \u{2014} \u{1F389}&nbsp;end</p>",
		'out' => "<p>Za\u{17C}\u{F3}\u{142}\u{107} & \u{201C}curly\u{201D} \u{2014} \u{1F389}\u{A0}end</p>\n",
	],
	'g2_null' => [
		'in'  => "<p>&#0;</p>",
		'out' => "<p>\u{FFFD}</p>\n",
	],
	'g2_surrogate' => [
		'in'  => "<p>&#55296;</p>",
		'out' => "<p>\u{FFFD}</p>\n",
	],
	'g2_fdd0' => [
		'in'  => "<p>&#64976;</p>",
		'out' => "<p>\u{FDD0}</p>\n",
	],
	'g2_replacement' => [
		'in'  => "<p>&#65533;</p>",
		'out' => "<p>\u{FFFD}</p>\n",
	],
	'g2_fffe' => [
		'in'  => "<p>&#65534;</p>",
		'out' => "<p>\u{FFFE}</p>\n",
	],
	'g2_ffff' => [
		'in'  => "<p>&#65535;</p>",
		'out' => "<p>\u{FFFF}</p>\n",
	],
	'g2_10fffd' => [
		'in'  => "<p>&#1114109;</p>",
		'out' => "<p>\u{10FFFD}</p>\n",
	],
	'g2_10fffe' => [
		'in'  => "<p>&#1114110;</p>",
		'out' => "<p>\u{10FFFE}</p>\n",
	],
	'g2_10ffff' => [
		'in'  => "<p>&#1114111;</p>",
		'out' => "<p>\u{10FFFF}</p>\n",
	],
	'g2_out_of_range' => [
		'in'  => "<p>&#1114112;</p>",
		'out' => "<p>\u{FFFD}</p>\n",
	],
	'g3_escaped_script' => [
		'in'  => "<p>&lt;script&gt;alert(1)&lt;/script&gt;</p>",
		'out' => "<p><script>alert(1)</script></p>\n",
	],
	'g3_escaped_img_onerror' => [
		'in'  => "<p>&lt;img src=x onerror=alert(1)&gt;</p>",
		'out' => "<p><img src=x onerror=alert(1)></p>\n",
	],
	'g3_quot_in_attribute' => [
		'in'  => "<a title=\u{22}a&quot; onmouseover=&quot;alert(1)\u{22}>x</a>",
		'out' => "<a title=\u{22}a\u{22} onmouseover=\u{22}alert(1)\u{22}>x</a>\n",
	],
	'g3_apos_in_attribute' => [
		'in'  => "<a title=\u{22}a&#039;b\u{22}>x</a>",
		'out' => "<a title=\u{22}a'b\u{22}>x</a>\n",
	],
	'g3_lt_in_attribute' => [
		'in'  => "<a title=\u{22}a&lt;b\u{22}>x</a>",
		'out' => "<a title=\u{22}a<b\u{22}>x</a>\n",
	],
	'g3_script_body' => [
		'in'  => "<script>if (a &amp;&amp; b &lt; c) x(\u{22}&quot;\u{22});</script>",
		'out' => "<script>if (a && b < c) x(\u{22}\u{22}\u{22});</script>\n",
	],
	'g3_style_body' => [
		'in'  => "<style>a[title=\u{22}&quot;\u{22}] { color: red; }</style>",
		'out' => "<style>a[title=\u{22}\u{22}\u{22}] { color: red; }</style>\n",
	],
	'g3_textarea' => [
		'in'  => "<textarea>&lt;b&gt; &amp; \u{E9}</textarea>",
		'out' => "<textarea><b> & \u{E9}</textarea>\n",
	],
	'g3_pre' => [
		'in'  => "<pre>&lt;tag&gt; &amp;amp;</pre>",
		'out' => "<pre><tag> &amp;</pre>\n",
	],
	'g4_unclosed_tag' => [
		'in'  => "<p>unclosed",
		'out' => "<p>unclosed</p>\n",
	],
	'g4_crossed_tags' => [
		'in'  => "<p><b>x</p></b>",
		'out' => "<p><b>x</b></p>\n",
	],
	'g4_stray_lt' => [
		'in'  => "<p>a < b</p>",
		'out' => "<p>a < b</p>\n",
	],
	'g4_stray_gt' => [
		'in'  => "<p>a > b</p>",
		'out' => "<p>a > b</p>\n",
	],
	'g4_comment_with_entity' => [
		'in'  => "<p>x</p><!-- &amp; comment -->",
		'out' => "<p>x</p><!-- & comment -->\n",
	],
	'g4_cdata' => [
		'in'  => "<p><![CDATA[a & b]]></p>",
		'out' => "<p><!--[CDATA[a & b]]--></p>\n",
	],
	'g4_empty' => [
		'in'  => "",
		'out' => "\n",
	],
	'g4_text_only' => [
		'in'  => "plain text",
		'out' => "plain text\n",
	],
	'g5_rtl_arabic' => [
		'in'  => "<p>\u{645}\u{631}\u{62D}\u{628}\u{627} \u{628}\u{627}\u{644}\u{639}\u{627}\u{644}\u{645}</p>",
		'out' => "<p>\u{645}\u{631}\u{62D}\u{628}\u{627} \u{628}\u{627}\u{644}\u{639}\u{627}\u{644}\u{645}</p>\n",
	],
	'g5_rtl_hebrew' => [
		'in'  => "<p>\u{5E9}\u{5DC}\u{5D5}\u{5DD} \u{5E2}\u{5D5}\u{5DC}\u{5DD}</p>",
		'out' => "<p>\u{5E9}\u{5DC}\u{5D5}\u{5DD} \u{5E2}\u{5D5}\u{5DC}\u{5DD}</p>\n",
	],
	'g5_bidi_controls' => [
		'in'  => "<p>a\u{200E}b\u{200F}c\u{202B}d\u{202C}e</p>",
		'out' => "<p>a\u{200E}b\u{200F}c\u{202B}d\u{202C}e</p>\n",
	],
	'g5_cjk' => [
		'in'  => "<p>\u{65E5}\u{672C}\u{8A9E}\u{306E}\u{30C6}\u{30AD}\u{30B9}\u{30C8}</p>",
		'out' => "<p>\u{65E5}\u{672C}\u{8A9E}\u{306E}\u{30C6}\u{30AD}\u{30B9}\u{30C8}</p>\n",
	],
	'g5_nfc_precomposed' => [
		'in'  => "<p>\u{E9}</p>",
		'out' => "<p>\u{E9}</p>\n",
	],
	'g5_nfd_combining' => [
		'in'  => "<p>e\u{301}</p>",
		'out' => "<p>e\u{301}</p>\n",
	],
	'g5_vietnamese' => [
		'in'  => "<p>Ti\u{1EBF}ng Vi\u{1EC7}t nghi\u{EA}ng</p>",
		'out' => "<p>Ti\u{1EBF}ng Vi\u{1EC7}t nghi\u{EA}ng</p>\n",
	],
	'g5_raw_nbsp' => [
		'in'  => "<p>a\u{A0}b</p>",
		'out' => "<p>a\u{A0}b</p>\n",
	],
	'g5_soft_hyphen' => [
		'in'  => "<p>sig\u{AD}nal</p>",
		'out' => "<p>sig\u{AD}nal</p>\n",
	],
	'g6_inline_svg' => [
		'in'  => "<svg viewBox=\u{22}0 0 10 10\u{22}><title>A &amp; B</title><path d=\u{22}M0 0\u{22}/></svg>",
		'out' => "<svg viewbox=\u{22}0 0 10 10\u{22}><title>A & B</title><path d=\u{22}M0 0\u{22}></path></svg>\n",
	],
	'g6_svg_with_accent' => [
		'in'  => "<svg><title>Za\u{17C}\u{F3}\u{142}\u{107} \u{E9}</title></svg>",
		'out' => "<svg><title>Za\u{17C}\u{F3}\u{142}\u{107} \u{E9}</title></svg>\n",
	],
	'g7_straight_and_curly' => [
		'in'  => "<p>She said \u{22}hi\u{22} and 'bye' then \u{201C}hi\u{201D} and \u{2018}bye\u{2019} and it\u{2019}s fine</p>",
		'out' => "<p>She said \u{22}hi\u{22} and 'bye' then \u{201C}hi\u{201D} and \u{2018}bye\u{2019} and it\u{2019}s fine</p>\n",
	],
	'g7_polish_both_cases' => [
		'in'  => "<p>ZA\u{17B}\u{D3}\u{141}\u{106} G\u{118}\u{15A}L\u{104} JA\u{179}\u{143} / za\u{17C}\u{F3}\u{142}\u{107} g\u{119}\u{15B}l\u{105} ja\u{17A}\u{144} / \u{104}\u{106}\u{118}\u{141}\u{143}\u{D3}\u{15A}\u{179}\u{17B} \u{105}\u{107}\u{119}\u{142}\u{144}\u{F3}\u{15B}\u{17A}\u{17C}</p>",
		'out' => "<p>ZA\u{17B}\u{D3}\u{141}\u{106} G\u{118}\u{15A}L\u{104} JA\u{179}\u{143} / za\u{17C}\u{F3}\u{142}\u{107} g\u{119}\u{15B}l\u{105} ja\u{17A}\u{144} / \u{104}\u{106}\u{118}\u{141}\u{143}\u{D3}\u{15A}\u{179}\u{17B} \u{105}\u{107}\u{119}\u{142}\u{144}\u{F3}\u{15B}\u{17A}\u{17C}</p>\n",
	],
	'g7_typographic' => [
		'in'  => "<p>\u{A9} \u{AE} \u{2122} \u{B0} \u{BD} \u{20AC} \u{A3} \u{A5} \u{A7} \u{B6} \u{2020} \u{2021} \u{2022} \u{2026} \u{2030} \u{B1} \u{D7} \u{F7} \u{2260} \u{2264} \u{2265} \u{2192} \u{2190} \u{2194}</p>",
		'out' => "<p>\u{A9} \u{AE} \u{2122} \u{B0} \u{BD} \u{20AC} \u{A3} \u{A5} \u{A7} \u{B6} \u{2020} \u{2021} \u{2022} \u{2026} \u{2030} \u{B1} \u{D7} \u{F7} \u{2260} \u{2264} \u{2265} \u{2192} \u{2190} \u{2194}</p>\n",
	],
	'g7_data_json_single' => [
		'in'  => "<div data-config='{\u{22}title\u{22}:\u{22}Za\u{17C}\u{F3}\u{142}\u{107}\u{22},\u{22}q\u{22}:\u{22}say \u{5C}\u{22}hi\u{5C}\u{22}\u{22},\u{22}n\u{22}:1,\u{22}ok\u{22}:true}'>x</div>",
		'out' => "<div data-config=\u{22}{\u{22}title\u{22}:\u{22}Za\u{17C}\u{F3}\u{142}\u{107}\u{22},\u{22}q\u{22}:\u{22}say \u{5C}\u{22}hi\u{5C}\u{22}\u{22},\u{22}n\u{22}:1,\u{22}ok\u{22}:true}\u{22}>x</div>\n",
	],
	'g7_data_json_escaped' => [
		'in'  => "<div data-config=\u{22}{&quot;title&quot;:&quot;A &amp; B&quot;,&quot;n&quot;:1}\u{22}>x</div>",
		'out' => "<div data-config=\u{22}{\u{22}title\u{22}:\u{22}A & B\u{22},\u{22}n\u{22}:1}\u{22}>x</div>\n",
	],
	'g7_data_mixed_attrs' => [
		'in'  => "<button data-a=\u{22}1\u{22} data-label=\u{22}Za\u{17C}\u{F3}\u{142}\u{107} \u{201C}x\u{201D}\u{22} data-json='{\u{22}k\u{22}:\u{22}v & w\u{22}}' aria-label=\u{22}It\u{2019}s\u{22}>go</button>",
		'out' => "<button data-a=\u{22}1\u{22} data-label=\u{22}Za\u{17C}\u{F3}\u{142}\u{107} \u{201C}x\u{201D}\u{22} data-json=\u{22}{\u{22}k\u{22}:\u{22}v & w\u{22}}\u{22} aria-label=\u{22}It\u{2019}s\u{22}>go</button>\n",
	],
	'g7_data_url_and_json' => [
		'in'  => "<a href=\u{22}/x?a=1&amp;b=2&amp;c=%20\u{22} data-track='{\u{22}u\u{22}:\u{22}/x?a=1&b=2\u{22}}'>l</a>",
		'out' => "<a href=\u{22}/x?a=1&b=2&c=%20\u{22} data-track=\u{22}{\u{22}u\u{22}:\u{22}/x?a=1&b=2\u{22}}\u{22}>l</a>\n",
	],
	'g7_kitchen_sink' => [
		'in'  => "<div class=\u{22}c\u{22} data-cfg='{\u{22}t\u{22}:\u{22}Za\u{17C}\u{F3}\u{142}\u{107} & \u{201C}curly\u{201D}\u{22},\u{22}d\u{22}:\u{22}\u{2014}\u{22}}'><p>He said \u{22}it\u{2019}s\u{22} \u{2014} \u{1F389} &amp; &nbsp;done</p></div>",
		'out' => "<div class=\u{22}c\u{22} data-cfg=\u{22}{\u{22}t\u{22}:\u{22}Za\u{17C}\u{F3}\u{142}\u{107} & \u{201C}curly\u{201D}\u{22},\u{22}d\u{22}:\u{22}\u{2014}\u{22}}\u{22}><p>He said \u{22}it\u{2019}s\u{22} \u{2014} \u{1F389} & \u{A0}done</p></div>\n",
	],
];
