<?php
/**
 * Regenerates encoding.php from the CURRENT implementation.
 *
 * Run: php tests/phpunit/unit/fixtures/generate.php
 *
 * This records what ships TODAY, defects included. Every regenerated golden must be
 * reviewed by hand before committing. Group g3 records escaped markup becoming live markup
 * and g7 records JSON data attributes being broken out of their own quotes; both are pinned
 * deliberately, not endorsed. See the security finding in
 * docs/superpowers/specs/2026-07-30-wordpress-phpunit-suite-design.md.
 *
 * Goldens are written as \u{...} escapes rather than raw UTF-8 so they survive copy/paste
 * and so a U+00A0 can never be mistaken for a space in review.
 */

defined( 'ABSPATH' ) || define( 'ABSPATH', sys_get_temp_dir() . '/' );

if ( ! function_exists( 'add_filter' ) ) {
	/**
	 * @return void
	 */
	function add_filter() {}
	/**
	 * @return void
	 */
	function add_action() {}
}

require_once dirname( __DIR__, 4 ) . '/lib/functions/utilities.php';

/**
 * Escape everything outside printable ASCII, plus the three characters that are special
 * inside a PHP double-quoted string.
 *
 * @param string $string Raw string.
 *
 * @return string
 */
function mai_test_escape( string $string ): string {
	$chars = preg_split( '//u', $string, -1, PREG_SPLIT_NO_EMPTY );

	// Invalid UTF-8 cannot be split by codepoint. Fall back to per-byte escapes so the
	// golden is still exact and still reviewable.
	if ( false === $chars ) {
		$out = '';
		foreach ( str_split( $string ) as $byte ) {
			$out .= sprintf( '\x%02X', ord( $byte ) );
		}
		return $out;
	}

	$out = '';

	foreach ( $chars as $char ) {
		if ( "\n" === $char ) {
			$out .= '\n';
			continue;
		}

		if ( "\t" === $char ) {
			$out .= '\t';
			continue;
		}

		$code = mb_ord( $char, 'UTF-8' );

		if ( false !== $code && 0x20 <= $code && 0x7E >= $code && ! in_array( $char, [ '\\', '"', '$' ], true ) ) {
			$out .= $char;
			continue;
		}

		$out .= sprintf( '\u{%X}', $code );
	}

	return $out;
}

/**
 * Canonicalizes attribute quoting so goldens do not depend on the libxml build that
 * generated them.
 *
 * libxml 2.15 normalizes attributes to double quotes and escapes inner double quotes as
 * &quot;. Older libxml preserves the source quote character. Both parse identically, so this
 * is serialization style rather than behavior, but without normalizing it here the goldens
 * pin whoever ran this script and fail everywhere else. DomEncodingTest applies the same
 * transform to both sides when comparing.
 *
 * @param string $html Serialized HTML.
 *
 * @return string
 */
function mai_test_canonical( string $html ): string {
	return preg_replace_callback(
		"/(\s[a-zA-Z][a-zA-Z0-9-]*)='([^']*)'/",
		static fn ( array $match ): string => $match[1] . '="' . str_replace( '"', '&quot;', $match[2] ) . '"',
		$html
	);
}

$cases = require __DIR__ . '/inputs.php';

$php  = "<?php\n";
$php .= "/**\n";
$php .= " * GENERATED by generate.php. Do not hand-edit goldens.\n";
$php .= " *\n";
$php .= " * Characterization of mai_get_dom_document() + mai_get_dom_html() as they ship TODAY,\n";
$php .= " * defects included. Groups g3 and g7 pin dangerous behavior deliberately; see the\n";
$php .= " * security finding in docs/superpowers/specs/2026-07-30-wordpress-phpunit-suite-design.md.\n";
$php .= " */\n\nreturn [\n";

// Record the libxml build. Some rows, notably the g2 noncharacter group, serialize
// differently by version: 2.15 preserves noncharacters, older builds drop them entirely.
// DomEncodingTest skips those rows when the running libxml differs rather than failing.
$php .= sprintf( "\t'_meta' => [ 'libxml' => '%s' ],\n", LIBXML_DOTTED_VERSION );

foreach ( $cases as $key => $in ) {
	$out  = mai_test_canonical( mai_get_dom_html( mai_get_dom_document( $in ) ) );
	$php .= sprintf(
		"\t%s => [\n\t\t'in'  => \"%s\",\n\t\t'out' => \"%s\",\n\t],\n",
		var_export( $key, true ),
		mai_test_escape( $in ),
		mai_test_escape( $out )
	);
}

$php .= "];\n";

file_put_contents( __DIR__ . '/encoding.php', $php );

printf( "Wrote %d cases to encoding.php\n", count( $cases ) );
